project_id = "xqcelwxqavzmgaqcgqps"

[functions.offerwall-postback]
verify_jwt = false

[functions.vortexwall-postback]
verify_jwt = false

[functions.primewall-postback]
verify_jwt = false

[functions.offery-postback]
verify_jwt = false

[functions.notik-postback]
verify_jwt = false

[functions.radientwall-postback]
verify_jwt = false
