import { Clock, DollarSign, TrendingUp } from 'lucide-react';

const StatsSection = () => {
  return (
    <section className="py-8 px-4">
      <div className="bg-muted rounded-2xl p-6 relative overflow-hidden">
        {/* Background decoration */}
        <div className="absolute inset-0 opacity-20">
          <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-r from-orange-400 via-blue-400 to-blue-600" />
        </div>
        
        <div className="relative grid grid-cols-3 gap-4 text-center">
          <div>
            <div className="flex items-center justify-center gap-1 text-primary font-bold text-xl md:text-2xl">
              <Clock className="w-5 h-5" />
              <span>00h</span>
            </div>
            <div className="text-primary font-bold text-xl md:text-2xl">00m</div>
            <p className="text-xs text-muted-foreground mt-1">
              Average Time<br />Until First Cashout
            </p>
          </div>
          
          <div>
            <div className="text-white font-bold text-xl md:text-2xl">$0.00</div>
            <p className="text-xs text-muted-foreground mt-1">
              Yesterday's Per-<br />User Earning<br />Performance
            </p>
          </div>
          
          <div>
            <div className="text-white font-bold text-xl md:text-2xl">$0.00</div>
            <p className="text-xs text-muted-foreground mt-1">
              Total Revenue<br />Generated by<br />WallsCash
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default StatsSection;
