import { Clock, DollarSign, TrendingUp } from 'lucide-react';
import statsIllustrationDefault from '@/assets/stats-illustration.png';
import { useSiteSettings } from '@/contexts/SiteSettingsContext';

const StatsSection = () => {
  const { homepageImages } = useSiteSettings();
  const statsIllustration = homepageImages.statsIllustration || statsIllustrationDefault;
  
  return (
    <section className="py-10 px-4">
      <div 
        className="rounded-2xl p-6 md:p-8 relative overflow-hidden max-w-4xl mx-auto"
        style={{ background: '#0E1625' }}
      >
        <div className="relative flex flex-col md:flex-row items-center gap-6">
          {/* Illustration */}
          <div className="flex-shrink-0">
            <img 
              src={statsIllustration} 
              alt="Earning illustration" 
              className="w-32 h-32 md:w-40 md:h-40 object-contain drop-shadow-lg"
            />
          </div>
          
          {/* Stats Grid */}
          <div className="flex-1 grid grid-cols-3 gap-6 md:gap-[100px] text-center">
            <div>
              <div className="flex items-center justify-center gap-1 font-bold text-xl md:text-3xl" style={{ color: '#1DBF73' }}>
                <Clock className="w-5 h-5 md:w-6 md:h-6" />
                <span>00h</span>
              </div>
              <div className="font-bold text-xl md:text-3xl" style={{ color: '#1DBF73' }}>00m</div>
              <p className="text-xs md:text-sm mt-2" style={{ color: '#8FA3B8' }}>
                Average Time<br />Until First Cashout
              </p>
            </div>
            
            <div>
              <div className="font-bold text-xl md:text-3xl text-foreground">$0.00</div>
              <p className="text-xs md:text-sm mt-2" style={{ color: '#8FA3B8' }}>
                Yesterday's Per-<br />User Earning<br />Performance
              </p>
            </div>
            
            <div>
              <div className="font-bold text-xl md:text-3xl text-foreground">$0.00</div>
              <p className="text-xs md:text-sm mt-2" style={{ color: '#8FA3B8' }}>
                Total Revenue<br />Generated by<br />WallsCash
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default StatsSection;
